#YOUR_TUSHARE_KEY
tushare_key: "" 

#YOUR_BOCHA_KEY
bocha_key: "" 

#YOUR_SERP_KEY
serp_key: "" 

#YOUR_FMP_KEY
fmp_key: ""

#YOUR_FINNHUB_KEY
finnhub_key: "" 

#YOUR_ALPHA_VANTAGE_KEY
alpha_vantage_key: ""

# YOUR_POLYGON_KEY
polygon_key: ""

llm:
  base_url: "https://api.deepseek.com"
  api_key: "" #YOUR_DEEPSEEK_API_KEY
  model_name: "deepseek-chat"

llm_thinking:
  base_url: "https://api.deepseek.com"
  api_key: "" #YOUR_DEEPSEEK_API_KEY
  model_name: "deepseek-reasoner"

vlm:
  base_url: "https://api.stepfun.com/v1"
  api_key: "" #YOUR_STEPFUN_API_KEY
  model_name: "step-1o-turbo-vision"

# US Market specific data agents configuration
data_agents_config:
  - agent_name: "us_polygon_news"
    data_source_list: 
      - "data_source.us_polygon_news.USPolygonNews"
  - agent_name: "us_price_market"
    data_source_list: 
      - "data_source.us_price_market.USPriceMarket"

# US Market specific research agent configuration  
research_agent_config:
  belief_list_path: "config/belief_list.json"
  max_react_step: 10
  output_language: "English"
  tools:
    - "tools.stock_symbol_search_us.stock_symbol_search"
    - "tools.corp_info_us.company_financial_info"
    - "tools.price_info_us.price_info"
    - "tools.search_web.search_web"
    - "tools.stock_summary_us.stock_summary"
    - "tools.final_report.final_report"

market_config_file: "config/market_config_us.yaml"

system_language: "English"

researcher_contest_config:
  contest_mode: False
  judger_config: llm
  num_judgers: 3
  window_m: 3
  window_n: 3